title: "Tech Support"
body:
  - type: input
    id: user
    attributes:
      label: User
      description: Link to the profile of or the thread with the user
  - type: textarea
    id: links
    attributes:
      label: Relevant links
      description: "Any helpful links. E.g., a client site, test site, internal or external documentation."
      render: bash
  - type: textarea
    id: description
    attributes:
      label: Describe the problem or question
